export let artists = [
    {photo:"../../imagenes/power-glove.jpg",
history:"holi"},
    {photo:"../../imagenes/Bassnectar.jpg",
    history:"holi"},
    {photo:"../../imagenes/crystal-castles.jpg",
    history:"holi"},
    {photo:"../../imagenes/daft-punk.jpg",
    history:"holi"},
    {photo:"../../imagenes/dvrst.jpg",
    history:"holi"},
    {photo:"../../imagenes/gabriela robin.jpg",
    history:"holi"},
    {photo:"../../imagenes/notfound.jpg",
    history:"holi"},
    {photo:"../../imagenes/slipknot.jpg",
    history:"holi"},
    {photo:"../../imagenes/tinlicker.jpg",
    history:"holi"},
    {photo:"../../imagenes/astronaut.jpg",
    history:"holi"}
]